### ISSUE TITLE
Image Correlation Error

### ISSUE THREAD

**Issue by xhdxgg** [SaifAati/Geospatial-COSICorr3D#4]
Hello, using a rectangular window in the image correlation process, the result is the following error ' Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)', while the square correlation window is running correctly. Why is this happening?
<img width="490" alt="1670672459(1)" src="https://user-images.githubusercontent.com/90568641/206853223-1465049e-9d27-4454-9ff3-d1b6ac77b927.png">

**Comment by SaifAati** [comment]
Thank you, for raising this issue. There are some caveats when using a step size of less than 4 for the frequency correlator, but I am not sure about the spatial correlator. Would it be possible to try a rectangular window with a step size (of 8,8)?
I will do some tests on my end and post the results.
