### ISSUE TITLE
CosiCorr libraries are not being accessed in anaconda environment 

### ISSUE THREAD

**Issue by Muradict** [SaifAati/Geospatial-COSICorr3D#7]
For linux, instead of adding the following to the .bashrc file:
```
LD_LIBRARY_PATH=~/geoCosiCorr3D/lib/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH
```
You will have to add instead
```
LD_LIBRARY_PATH=~/Geospatial-COSICorr3D/geoCosiCorr3D /lib/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH

```
This fixed the issue for me given that I did clone the CosiCorr3D repository to the home directory (cd ~).

**Comment by SaifAati** [comment]
Fixed in geoCosiCorr V2.4.1
